name: environment
channels:
  - conda-forge
dependencies:
  - python=2.7.16
  - numpy=1.16.4
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - nglview=1.0.b2
  - mdanalysis=0.19.2
